backbee/backbee-php

composer.json
``0.7.*@dev`` branch of ``respect/validation`` dependencies no longer exists.
This pull request update to the latest "stable" ``0.6.x`` branch.
=> [RFR] - Updated respect/validation version to last stable

Installer/EntityFinder.php, Services/Local/Media.php
This method built valid namespace for BackBee when it was located on project's root. But it does not do the job anymore since backbee/backbee moved into vendor folder.
=> [WIP] [Installer] #162 update EntityFinder::getNamespace method

BBApplication.php
Updated BBApplication::getClassContentDir() to use getBBDir method instead of getBaseDir to build path of core classcontent directory. More details: #165
=> [RFR] #165 + updated BBApplication::getClassContentDir

Config/security.yml
We want to remove every reference to this project old name (BackBuilder, BackBuilder5, bb5).
=> [RFR] [Config] #172 + updated security.yml to request 'secret_key' instead of 'bb5_secret_key'

Bundle/AbstractBaseBundle.php, Bundle/BundleInterface.php, Bundle/BundleLoader.php, CHANGELOG-0.12.md
Previously, we guessed bundle's service identifier from its base directory. This way works well until we move backbee into  ``vendor/``. This implies that we have no control about service identifier. To ease access to these request, we calculate bundle's service identifier with the identifier provided in application bundle configuration section.
=> [RFR] [Bundle] #178 AbstractBaseBundle, BundleInterface and BundleLoader update to fix an issue introduced by moving core into vendor's folder

ClassContent/AClassContent.php, ClassContent/AContent.php, ClassContent/Category.php, ClassContent/ContentSet.php, Config/route.yml, Controller/Controller.php, Rest/Controller/ARestController.php, Rest/Controller/AclController.php, Rest/Controller/BundleController.php, Rest/Controller/ClassContentController.php, Rest/Controller/GroupController.php, Rest/Controller/LayoutController.php, Rest/Controller/PageController.php, Rest/Controller/SecurityController.php, Rest/Controller/TestController.php, Rest/Controller/UserController.php
This option is passed as query parameter; it's necessary to lighten get classcontent action response;
The reduction is done by unsetting classcontent entry provided by classcontent definition (like maxentry, minentry, accept and properties)
I did some benchmarks:
- get article collection (26 items) with verbose true: response with over 20k lines
- get article collection (26 items) with verbose false: response with ~9k lines
It still heavy so we have to discuss about this with @crouillon.
=> [RFR] [ClassContent] #63 + add verbose filter to getAction() and getCollectionAction() of ClassContentController

ClassContent/Category.php, Config/route.yml, Rest/Controller/AclController.php, Rest/Controller/ClassContentController.php, Rest/Test/RestTestCase.php, Rest/Tests/Controller/ClassContentControllerTest.php, Rest/Tests/Controller/UserControllerTest.php, Tests/TestCase.php
Currently, to get all classcontent's categories:
``/rest/{version}/classcontent/category``
And to get classcontent's specific category:
``/rest/{version}/classcontent/category/{id}``
This PR change these patterns:
- from ``/rest/{version}/classcontent/category`` to ``/rest/{version}/classcontent-category``
- from ``/rest/{version}/classcontent/category/{id}`` to ``/rest/{version}/classcontent-category/{id}``
These changes occur to avoid conflict with __get classcontent by type pattern__: ``/rest/{version}/classcontent/{type}``
=> [RFR] [Rest] #176 changed classcontent's category route pattern

.travis.yml
Removed PHP 5.6 from ``allow_failure`` section and updated composer version.
=> #194 + updated .travis.yml to get last version of composer

composer.json
Some updates are very effective like ``twig`` which improve the cache management or ``symfony`` which brings improvements about security.
Note that ``doctrine/dbal`` breaks compatibilty with backbee since version >= 2.5. I didn't test with ``doctrine/orm`` version 2.5 or later yet cause it still in alpha release.
=> [RFR] #196 + updated composer.json and project's dependencies

NestedNode/Repository/PageRepository.php, NestedNode/Tests/Repository/PageRepositoryTest.php
This enhancement is for ease getRoot function in mono site configuration.
But if there is multiple site enabled getRoot have to raise an exception in case of site is null.
=> Add optional site parameter in getRoot function #210

.travis.yml, ClassContent/Tests/ClassContentTest.php, NestedNode/Tests/MediaTest.php
Sometimes, travis complains about dependencies we don't have! https://travis-ci.org/backbee/BackBee/jobs/48606764
This is a suggested patch.
**In 0.11.* autoloading in travis does'nt work. At this point, because we don't plan to maintain 0.11 branch, I've decided to skip tests that does'nt not work on travis BECAUSE element\text class not found.**
@eric-chau : you should backport this one to ``master`` branch.
=> [WIP]Resolved weird issue on travis

AutoLoader/AutoLoader.php, BBApplication.php, Logging/Logger.php, composer.json
See #244
This will uncouple error/exception handling from rendering, and also I've added the new [Symfony VarDumper](http://symfony.com/blog/new-in-symfony-2-6-vardumper-component) which is very powerfull to debug, and also it won't break the script.
=> [RFR] - Uncouple Logger from errorHandler/exceptionHandler

Validator/Rules/Image.php
The autoloader expected class "BackBee\Validator\Rules\Image" to be defined in file "/vendor/backbee/backbee/Validator/Rules/Image.php". The file was found but the class was not in it, the class name or namespace probably has a typo.
=> #250 fix Error on autoloading class Backbee\Validator\Rules\Image

Config/events.yml, Config/services/error.yml, Config/services/services.yml, Event/Listener/ExceptionListener.php, FrontController/FrontController.php, Resources/layouts/error/404.phtml, Resources/layouts/error/500.phtml
I moved the exception management to a ``kernel.exception`` listener.
Also, imo we should be able to override the error templates because our clients always want a customised error page, with their own content and dependencies.
This is an actual POC, but I need a review and advices to improve my commits.
Finally, how can I test it ?
=> [RFR] Introduced a new way to execute and configure error pages

Renderer/Helper/dateHelper.php
- Use default timezone/culture if is not set into config
- Use a format "%Y-%m-%d at %H:%M" if is not set into config
- In initTimzone -> verify if config is an array before use array_key_exists function
=> [Renderer] + don't force to set timezone/culture/format in datehelper

Routing/RouteCollection.php
``BackBee\Routing\RouteCollection::getUri`` can return an invalid URL which contains ``\``, this PR brings fix that apply a ``str_replace`` to replace ``\`` by ``/``.
=> [RFR] [Routing] fixed RouteCollection::getUri to return valid url (replacing '\' by '/')

Renderer/Helper/metadata.php
Hi,
this follow the related issue on backbee standard: https://github.com/backbee/backbee-standard/issues/58 .
The SEO panel was correctly displayed but the metadata weren't written on HTML page. In my opinion, the API of Page object have been updated :)
I have updated the helper to make this work as expected.
=> Fixed metadata() helper for twig

NestedNode/Page.php
PR #331 introduced an issue to installation of  ``backbee-standard`` cause we setted Root page to state 3 (= online and hidden) but the test inside ``BackBee\NestedNode\Page::setState`` throws exception if the page is not strictly equal to ``BackBee\NestedNode\Page::STATE_ONLINE``.
=> [RFR] [NestedNode] fixed Page::setState to allow setting a root page to online and hidden state

ClassContent/Repository/ClassContentRepository.php
More details at #263. I also called ``array_map`` function to prevent error caused by PHP ``implode`` function.
=> [RFR] [ClassContent] fixed ClassContentRepository::getClassnames which performed bad query #263

NestedNode/Repository/PageRepository.php
As mentionned in #278, we must pass ``boolean false`` as second parameter of Doctrine Paginator constructor to to preserve the right collection items order.
=> [RFR] [NestedNode] updated PageRepository's calls to Doctrine Paginator constructor

ClassContent/AbstractClassContent.php, Workflow/State.php
Changed visibility of ``BackBee\ClassContent\AbstractClassContent::$_subcontent`` attribute from ``public`` to ``protected`` otherwise it can break Doctrine lazy-load mechanism.
Added ``inversedBy`` property to ``BackBee\Workflow\State::$_layout`` attribute annotation.
More details on #218.
=> [RFR] [ClassContent] [Workflow] fixed Doctrine mapping errors in AbstractClassContent and State #218

Bundle/BundleLoader.php
Updated ``BackBee\Bundle\BundleLoader::addClassContentDir`` to use ``BackBee\BBApplication::unshiftClassContentDir`` instead of ``BackBee\BBApplication::unshiftClassContentDir`` to allow bundle to override ``backbee/backbee`` core classcontent yaml file.
=> [Bundle] updated BundleLoader::addClassContentDir #164

Cache/NoCache/Cache.php
These ``TODO`` mention are not appropriate cause ``BackBee\Cache\NoCache\Cache`` is here to simulate a non cache system.
=> [Cache] removed TODO placeholder from NoCache\Cache class #95 #94 #93 #92 #91

Bundle/Registry/Builder.php
``BackBee\Bundle\Registry\Builder::buildRegistries`` called nonexistent method (``buildRegistryFromSomething()``) so this PR fixed it by raising an exception.
=> [Registry] updated Builder::buildRegistries to not call nonexistent method #90

ClassContent/Repository/ClassContentRepository.php, Rest/Controller/ClassContentController.php
@hbaptiste, I just fixed your bug about classcontent REST API ``::deleteAction()`` that does not remove the content. This is caused by the fact that I forgot to call ``Doctrine\ORM\EntityManager::flush()`` method, my apologizes to you.
=> [Rest] updated ClassContentController::deleteAction to call entity manager::flush()

Config/services/profiler.yml, Config/services/services.yml, Logging/DebugStackLogger.php, Profiler/EventListener/ToolbarListener.php, Resources/scripts/Collector/logger.html.twig
This closes https://github.com/backbee/backbee-standard/issues/135.
* Logs are now displayed
* Logs count are now displayed
I think for the future we need to think about use the Symfony's profiler instead of our own.
Time data collector remains inactive and should be part of another issue.
=> Closes #135 - fix debug panel displaying

ClassContent/ClassContentManager.php, Config/events.yml, Event/Listener/ClassContentListener.php
Added ``BackBee\Event\Listener\ClassContentListener::onFlushPage`` to catch everytime we are persisting a new page event. We are looking for any default classcontent (when the main node is the current page)to create its draft. We also apply the same logic to the default content's subcontents.
This is useful to allow commit of default classcontent with ClassContent REST API.
=> [ClassContent] added listener for 'nestednode.page.onflush' event #324

ClassContent/ClassContentManager.php, Config/events.yml, Event/Listener/RevisionListener.php
Updated ``BackBee\Event\Listener\RevisionListener::onFlushElementFile`` to listen ``revision.onflush`` instead of ``revision.preflush``.
=> [ClassContent] updated RevisionListener::onFlushElementFile

NestedNode/Repository/PageRepository.php, NestedNode/Tests/Repository/PageRepositoryTest.php, Resources/layouts/error/default.phtml, Rest/Controller/PageController.php, Rest/Tests/Controller/PageControllerTest.php, Rewriting/UrlGenerator.php
refs https://github.com/backbee/backbee-standard/issues/113
Duplication of a page doesn't generate a new url for the newly duplicated page.
=> Fix page duplication

Event/Listener/RevisionListener.php
The move of the file has to be done only in case that the file's path is valid, else it will throw an exception.
=> [ClassContent] stop RevisionListener::onFlushElementFile execution if the file's path is not valid

NestedNode/AbstractNestedNode.php, Rest/Controller/PageController.php, Rest/Tests/Controller/PageControllerTest.php
this pull request is needed by BbCoreJs to get the information about ``isRoot()`` of a Page.
refs: https://github.com/backbee/BbCoreJs/issues/439
=> Added option to return isRoot() value of Page from REST api

NestedNode/Page.php
Aims to fix [backbee/bb-core-js issue #470](https://github.com/backbee/BbCoreJs/issues/470).
This has to be done this way cause ``&`` on 0 will always return 0, that why there was a bug about offline and hidden state label.
=> [NestedNode] updated Page::getStateLabel to return right label for offline state

CHANGELOG-1.0.md, ClassContent/Indexation.php, ClassContent/Revision.php, Event/Listener/ClassContentListener.php, Event/Listener/IndexationListener.php, MetaData/MetaData.php, NestedNode/KeyWord.php, NestedNode/Media.php, Security/Authorization/Voter/BBAclVoter.php
Some references to ``BackBee\ClassContent\AClassContent`` still remain so I cleaned it. Also Updated some classes coding style.
=> Replaced reference to 'AClassContent' by 'AbstractClassContent'

ClassContent/AbstractContent.php, ClassContent/Element/File.yml, ClassContent/Element/Image.yml, ClassContent/Tests/ClassContentTest.php, ClassContent/Traits/Element/FileJsonSerializeTrait.php, ClassContent/Traits/Element/ImageJsonSerializeTrait.php, NestedNode/Media.php, Rest/Controller/MediaController.php, Rest/Controller/MediaFolderController.php
This PR aims to resolve [backbee/bb-core-js issue #414](https://github.com/backbee/BbCoreJs/issues/414).
Updated ``BackBee\ClassContent\AbstractContent::jsonSerialize`` to also return extra parameters. Added ``BackBee\ClassContent\Traits\Element\FileJsonSerializeTrait`` and ``BackBee\ClassContent\Traits\Element\ImageJsonSerializeTrait`` to ``file_size``, ``image_width`` and ``image_height`` extra parameters.
=> [ClassContent] AbstractContent::jsonSerialize also return extra parameter

Event/Listener/CacheListener.php
changed from ``cache.control`` to ``cache.content`` for more coherence with page cache service (which is named ``cache.page``).
This also disable by default content cache.
=> [Cache] fixed content cache service name

ClassContent/ClassContentManager.php, NestedNode/Repository/MediaRepository.php, Rest/Controller/MediaController.php
Updated ``BackBee\ClassContent\ClassContentManager::prepareDraftForCommit`` to always commit all content's elements the first time (when content state is equals to ``1000`` - ``ClassContent::STATE_NEW``).
Also updated ``BackBee\Rest\Controller\MediaController::mediaToJson`` to also hydrate media main content elements draft otherwise we don't get the right image.
This issue aims to resolve [backbee/bb-core-js #570](https://github.com/backbee/BbCoreJs/issues/570).
=> [ClassContent] updated ClassContentManager::prepareDraftForCommit

ClassContent/Listener/ClassContentListener.php, ClassContent/Listener/IndexationListener.php, ClassContent/Listener/RevisionListener.php, Config/events.yml
Moved ClassContent listeners from Event component into ClassContent component and removed unused methods inside them. It's mainly listeners that listened to JsonRPC server events. Also see #347.
=> [ClassContent] moved ClassContent listeners and removed unused methods #347

Rest/Controller/ClassContentController.php
This PR aims to resolve issue #370 reported by @fkroockmann. It is triggered by ``ClassContentController::postAction`` which did not create draft for content's elements so the element's state never passed to ``AbstractClassContent::STATE_NORMAL``.
=> [Rest] updated ClassContentController::postAction to also create drafts for content's elements

ClassContent/Repository/ClassContentRepository.php
``BackBee\ClassContent\Repository\ClassContentRepository::findPagesByContent`` didn't pass the provided content uid to the query to get every linked pages, this PR fix it.
=> [ClassContent] fixed ClassContentRepository::findPagesByContent

BBApplication.php, Rest/Controller/SecurityController.php, Security/Authentication/Provider/BBAuthenticationProvider.php, Security/Authentication/Provider/PublicKeyAuthenticationProvider.php, Security/Token/BBUserToken.php, Tests/TestCase.php
Updated ``BackBee\Security\Token\BBUserToken`` to add ``::setLifetime`` and ``::isExpired`` methods. By this way we can ask the token itself if it is expired or not so ``BBApplication::getBBUserToken`` can invalidate session if the session is expired.
ping @crouillon, what do you think about it?
(This PR aims to resolve a part of [backbee/bb-core-js issue #522](https://github.com/backbee/BbCoreJs/issues/522))
=> [Security] updated BBUserToken API to provide ::isExpired method

ClassContent/Repository/ClassContentRepository.php
Fixed ``BackBee\ClassContent\Repository\ClassContentRepository``  to not replace contentset's element.
=> [ClassContent] fixed ClassContentRepository::deleteContent

NestedNode/Page.php
This is an API improvement.
Now Pages return an array of page statuses and not a string, we need to merge BbCoreJS pull request https://github.com/backbee/BbCoreJs/pull/767
=> Return code status and not bad strings

NestedNode/Page.php, Rest/Tests/Controller/PageControllerTest.php
* REST Page api now returns publishing/archiving dates in same format than created/modified.
* Added a simple test for PageControllerTest ``getAction``
This is resolution of this issue: https://github.com/backbee/BbCoreJs/issues/746
=> Fixed Page serialisation publishing/archiving

Rest/Controller/ClassContentController.php
Currently content's draft is not hydrated when we get content collection if we are logged, this PR fixes it.
=> [Rest] updated ClassContentController::findContentsByCriterias to also hydrate contents draft

ClassContent/Repository/ClassContentRepository.php, ClassContent/Tests/ClassContentPersistenceTest.php, Command/Tests/AclLoadCommandTest.php, Config/Tests/PersistorTest.php, Controller/Tests/ControllerResolverTest.php, DependencyInjection/Tests/ContainerBuilderTest.php, DependencyInjection/Tests/ContainerProxyTest.php, DependencyInjection/Tests/Listener/ContainerListenerTest.php, NestedNode/Tests/AbstractNestedNodeTest.php, NestedNode/Tests/KeyWordTest.php, NestedNode/Tests/MediaFolderTest.php, NestedNode/Tests/MediaTest.php, NestedNode/Tests/PageTest.php, NestedNode/Tests/PageUrlRewritingTest.php, NestedNode/Tests/Repository/NestedNodeQueryBuilderTest.php, NestedNode/Tests/Repository/NestedNodeRepositoryTest.php, NestedNode/Tests/Repository/PageQueryBuilderTest.php, NestedNode/Tests/Repository/PageRepositoryTest.php, Rest/Patcher/RightManager.php, Rest/Tests/Controller/AbstractRestControllerTest.php, Rest/Tests/Controller/ClassContentControllerTest.php, Tests/BackBeeTestCase.php, Tests/Mock/MockBBApplication.php, Tests/TestCase.php, Tests/TestKernel.php, Tests/bootstrap.php.dist
Created ``BackBee\Tests\BackBeeTestCase`` which is more consistent than ``BackBee\Tests\TestCase`` for several reasons:
- provide UNIQUE instance of ``BBMockApplication``
- autoloading BackBee test suite is now simple, just invoke ``BackBeeTestCase::prepare`` in bootstrap.php.dist (multiple calls is also prevented)
- API simplified and more useful
- removed unused methods
- massive improvements of database management
Also added ``BackBee\Tests\ClassContentPersistenceTest`` to test ClassContent and its revisions behavior on deletion and persistence process.
ping @crouillon and @mickaelandrieu, what do you think about it? First step is to have these two ``TestCase`` classes but we will quickly remove the old one and adapt every test class.
=> [Tests] created BackBeeTestCase which is more consistent and lightweight #394

Util/Doctrine/EntityManagerCreator.php
Cleaned ``Util\Doctrine\EntityManagerCreator`` and removed specific options added by Next developers.
=> [Util] cleaned EntityManagerCreator coding style and removed management of unused options

ClassContent/AbstractClassContent.php, ClassContent/Tests/ClassContentTest.php
Currently, if we set an empty value of param, the merge is not done correctly and keep the default value.
=> [ClassContent] Fix set an empty array for param

Site/Repository/LayoutRepository.php
When a layout picpath is null we try to unlink a folder that action create an infinite loop because the while condition stay every time true :
```php
true === file_exists($thumbnailfile) && true === is_writable($thumbnailfile)
```
To avoid this problem I have use `is_file` because it's more restrictive than `file_exists`.
=> [layout] Avoid infinite loop when picpath is egal to null

.scrutinizer.yml
Now Scrutinizer is allowed to fail the build if any major or security new issues are found.
=> Improve scrutinizer checks

BBApplication.php
``getNamespace()`` is no longer available for Bundles, so we need to reflect classes to get the namespace of Bundle.
=> Fixed Command autoloading for bundles

BBApplication.php, Config/services/services.yml, DependencyInjection/BootstrapResolver.php, DependencyInjection/ContainerProxy.php, DependencyInjection/Dumper/PhpArrayDumper.php, DependencyInjection/Tests/BootstrapResolverTest.php, DependencyInjection/Tests/ContainerProxyTest.php, DependencyInjection/Tests/Dumper/PhpArrayDumperTest.php, DependencyInjection/Tests/Dumper/PhpArrayDumperTest_Resources/services.yml, Stream/ClassWrapper/Adapter/Yaml.php
``Symfony\Component\DependencyInjection\Definition::[get|set]Factory[Method|Class|Service]()`` are now deprecated so this PR updated it to be compliant with this. This also improves:
- Remaining deprecation notices drop from ``43688`` to ``9267``
- Other deprecation notices drop from ``551`` to ``137``
=> [DependencyInjection] updated the way we handle service that depends on factory

Config/renderer.yml, Renderer/AbstractRendererAdapter.php, Renderer/Adapter/Twig.php, Renderer/Adapter/phtml.php, Renderer/Renderer.php, Renderer/RendererAdapterInterface.php, Renderer/Tests/Adapter/TwigTest.php, Renderer/Tests/Mock/FakeRendererAdapter.php, Renderer/Tests/Mock/TwigAdapter.php, Renderer/Tests/RendererTest.php
According to issue #480, this PR aims to resolve this by allowing ``BackBee\Renderer\Renderer`` to handle and pass to each adapters its custom configurations.
Note that this improvement support old and new version of adapters config declaration:
```yml
adapter: [\BackBee\Renderer\Adapter\Twig, \BackBee\Renderer\Adapter\phml]
```
new version: 
```yml
adapter: 
twig:
class: \BackBee\Renderer\Adapter\Twig
config: 
autoescape: false
phtml:
class: \BackBee\Renderer\Adapter\phml
config: [] # this entry is optional
```
A mix of both format is also supported =)
=> [RFR] [Renderer] Renderer can now handle custom config per adapter #480

Renderer/Renderer.php
This PR aims to ease access to application's translator into Renderer templates. Example in twig template:
- Before: ``{{ this.getApplication().getContainer().get('translator').trans('random_token') }}``
- Now: ``{{ bb.translator.trans('random_token') }}``
ping @ndufreche.
=> [RFR] [Renderer] added 'translator' to bb variable

Translation/Translator.php
Little typo fix on the "Resources" word
=> fixing typo into translator component

Rest/Controller/ClassContentController.php
I found this function: findContentsByCriterias them I have corrected and the function has deprecated.
=> Removing a cirteria typo in function name

NestedNode/Repository/PageQueryBuilder.php
Added missing method ``::andLayoutIs()`` into ``BackBee\NestedNode\Repository\PageQueryBuilder``.
ping @crouillon, is it intentional for you to remove it since this version or you simply forget it?
=> [RFR] [NestedNode] added method PageQueryBuilder::andLayoutIs()

Bundle/AbstractAdminBundleController.php, Bundle/AbstractBundle.php, Bundle/AbstractBundleController.php, Bundle/BundleControllerResolver.php, Bundle/BundleInterface.php, Bundle/Exception/BundleConfigurationException.php, Config/route.yml, Config/services/services.yml, Renderer/Helper/bundleAdminForm.php, Renderer/Helper/bundleAdminLink.php, Renderer/Helper/bundleAdminUrl.php, Rest/Controller/BundleController.php
The admin interface system, to help developer to ease develop bundle interface.
It's composed of:
- abstract bundle controller to automatize routing system
- 3 helper to build her admin URL by passing the bundle name, controller name and action name.
- `bundleAdminUrl` url générator
- `bundleAdminLink` add all html properties at your link to automated interactions
- `bundleAdminForm` same as bundleAdminLink but for forms
- `BundleControllerResolver` it's a new class to interact with bundle controller by passing just bundle name and controller name
- An upgrade of `accessBundleExposedRoutesAction` from `Rest\BundleController`
- And new configuration available to the bundle config file like
- `admin_controller` is an array how to declare your's controller
- `admin_entry_point` the entry …
=> [RFR][Bundle] Add abstract bundle controller

Event/Listener/ExceptionListener.php, Resources/scripts/Profiler/panel.html.twig, Resources/scripts/Profiler/toolbar.html.twig
When page is in 404 or 500 error, we don't have any information from debug toolbar.
This pull request activate toolbar when we display the Symfony debug response.
The UI is not perfect yet but this ask a refactoring of our debug toolbar (which is out of scope of the issue solved by this contribution).
Edit: I've added some styles, we may need a  new UI.
=> Debug toolbar is now available when error page

Bundle/BundleLoader.php, Bundle/Event/BundleInstallUpdateEvent.php, Console/Command/AbstractBundleCommand.php, Console/Command/BundleInstallAllCommand.php, Console/Command/BundleInstallCommand.php, Console/Command/BundleUpdateAllCommand.php, Console/Command/BundleUpdateCommand.php, DependencyInjection/Listener/ContainerListener.php
This PR aims to get every bundle command works again. I also moved the ``install`` and ``update`` process from ``AbstractBundle`` to ``BundleLoader`` so every class that extend ``AbstractBundle`` will be lighter.
During the installation or update of a bundle we also dispatch 4 new events: (considering for the example below that the bundle _id_ is ``demo``)
- ``bundle.demo.preinstall`` is dispatched before ``BundleLoader`` install bundle Doctrine entities
- ``bundle.demo.postinstall`` is dispatched after ``BundleLoader`` install bundle Doctrine entities
- ``bundle.demo.preupdate`` is dispatched before ``BundleLoader`` update bundle Doctrine entities
- ``bundle.demo.postupdate`` is dispatched after ``BundleLoader`` update bundle Doctrine entities
There is also two new class events, …
=> [Console] updated every bundle command

Config/route.yml, Rest/Controller/SiteController.php, Rest/Tests/Controller/SiteControllerTest.php
This is an method addition to rest site controller: getSiteCollection.
note: I'm not sure but I think getLayoutsAction method is unused and it can be removed because there is no route to bind this action.
=> Rest site controller

Controller/FrontController.php
I have noticed than all events are written in lower case except postcall events.
That PR fixed this problem
Before PR : `rest.controller.classcontentcontroller.getAction.postcall`
After PR : `rest.controller.classcontentcontroller.getaction.postcall`
=> [Controller] Fix controller event name

Bundle/AbstractAdminBundleController.php
I have replaced '$this->getBundle()' by '$this->bundle' in AbstractAdminBundleController.php
I have add render method for avoid admin templates overcharging behind bundles
=> [bundle] remove useless function call and overcharging renderer function 

NestedNode/Tests/PageUrlRewritingTest.php, Rewriting/UrlGenerator.php
Currently, if the url contain "+", the url generator create a duplicate url
=> [NestedNode] Fix generation of url with special characters like '+'

Event/Listener/ExceptionListener.php
REFS https://github.com/backbee/backbee-standard/issues/325
the idea is to make errors more usables **in debug mode** from Javascripts clients /c  @ndufreche
=> Improved error rendering messages for ajax requests

Controller/Controller.php, composer.json
If the component is not installed, we are unable to use ``Controller::createFromBuilder()``.
This contribution introduce an exception with an explicit message to solve the issue, and suggest the installation of Symfony Form component on Composer installation.
ping @eric-chau
=> Add form component as suggested dependency

ClassContent/AbstractContent.php, Logging/AdminLog.php, NestedNode/AbstractNestedNode.php, NestedNode/KeyWord.php, NestedNode/MediaFolder.php, NestedNode/Tests/Mock/MockNestedNode.php, Site/Layout.php, Site/Site.php, Util/BBAbstract/AbstractUidEntity.php, Workflow/State.php
I rewrite annotation to optimize length field for all uids which are in md5. 
I hope that will optimize memory allocation  for database requests. 
impacted class : 
- ClassContent/AbstractContent.php
- Logging/AdminLog.php
- NestedNode/AbstractNestedNode.php
- NestedNode/KeyWord.php
- NestedNode/MediaFolder.php
- NestedNode/Tests/Mock/MockNestedNode.php 
- Site/Layout.php
- Site/Site.php
- Util/BBAbstract/AbstractUidEntity.php
- Workflow/State.php
I add "length=32," on those fields.
=> [Entity] optimize length field for md5 uids

ClassContent/Tests/Listener/ClassContentListenerTest.php, Config/events.yml
I change getAction to getaction because all events are in lower case in events.yml and in ClassContent/Test/Listener
=> [Config] fix case for getaction.postcall in events.yml

ClassContent/ClassContentManager.php, Rest/Controller/ClassContentController.php
Updated `ClassContentManager::prepareElements()`  to handle array of values of an element. Example, if you want to add two keywords to an article:
```js
// PUT /rest/1/classcontent/Article/Aticle/d775e20c62b018d84c1a12229ef9477d
{
"elements": {
"keywords": [
{
"uid": "04b89c815c65bcde9be3b5fb28f72f64",
"type": "Element/Keyword"
},
{
"uid": "dee512eb518042412ea374f2e8c272e8",
"type": "Element/Keyword"
}
]
},
"type": "Article/Article",
"uid": "d775e20c62b018d84c1a12229ef9477d"
}
```
ping @crouillon, @fkroockmann.
=> [ClassContent] updated ClassContentManager::prepareElements()

Bundle/AbstractBundle.php
As discussed with some of the core team, we need this accessor to get translation files from Bundles.
Sorry for tests, there is no one I will try to cover the Bundle part in another pull request.
=> introduced getResourcesDirectory() in AbstractBundle

ClassContent/Element/Keyword.yml, NestedNode/Repository/KeyWordRepository.php
I have noticed than all parameters must be set in ClassContent (in lower case).
That PR fixed this problem for ClassContent/Element/Keyword
- Add parameters/objectkeyword in ClassContent/Element/Keyword as array
- Change name from 'objectKeyword' to 'objectkeyword' in NestedNode/Repository/KeyWordRepository
=> Fix bug objectKeyword does not a parameter

BBApplication.php
Currently if the addResourceDir is call before getResourceDir, the resource dirs are not initialize
=> Fix Resource dir

NestedNode/Repository/PageRepository.php
I don't know why but sometimes it's an instance of PageRepository that is returned as subcontent of content.
ping @eric-chau
=> fix clone action

Rest/Controller/ClassContentController.php
Currently we cannot re-render content on dynamical page cause the page uid is required by ``Rest\Controller\ClassContentController::getAction`` while this should not be.
=> [ClassContent] updated ::getAction() in REST controller 

Session/SessionConfigurator.php
Please note that the `bb_session` service is configured by `session` key /c @fkroockmann @eric-chau @crouillon
=> Make the session configuration optional

Session/PdoSessionHandlerFactory.php
Avoid the lock of the session when the session is persisted by the same connection as the application.
=> Updated the PdoSessionHandler configuration

Config/services/rest.yml, Rest/Metadata/Cache/BackBeeCache.php
The new adapter allows to store the serializer metadata cache via BackBee cache services (bootstrap by default defined in Config/services/rest.yml)
=> Add JMS metadata cache adapter BackBeeCache

BBApplication.php
SwiftMailer new SmtpTransport instance needs a security parameter to set the encryption 
security key becomes **mandatory** in Config/mailer.yml
> Don't forget to update documentation on merge
=> [SwiftMailer] Add security parameter to new SmtpTransport instance

BBApplication.php
Return `null` instead of `false` in case no encryption is detected in mailer.yml
=> [SwiftMailer] fix encryption if not set in mailer.yml config file

BBApplication.php, Bundle/Listener/BundleListener.php
We load every bundle's config only if the bundle loader is not restored. Tests on my side shows up an improvement of ~10 ms.
=> improved init of bundles in BBApplication when debug is setted to false

Config/events.yml, Renderer/Adapter/Twig.php, Renderer/Listener/TwigListener.php
PR #645 initiated by myself removed the `TwigListener` and the loading of Twig's extensions is done in `Adapter\Twig::__construct()`. It can introduce bug in some cases like if the `Renderer` is invoked very early. So this specific behavior must be reverted.
Also I moved the listener to listen `bbapplication.init` instead of `bbapplication.start` so even is CLI mode Renderer will be configured as expected.
=> [Renderer] added TwigListener::onApplicationReady() to load twig extensions

Rest/Controller/PageController.php
[PAGE MANAGEMENT] redefine and develop search on pages 
- new parameter added to make the difference between page list and page tree
- translation for label "No page found." are needed for this languages: chines, russian, german
=> #531 redefine and develop search on pages

Util/Sequence/Sequencer.php
We need to get a refreshed new value from database in a foreach loop for exemple.
The Doctrine cache avoids that till the Entity is not refreshed.
=> Sequencer : avoid Doctrine cache and force reading from database

Renderer/Helper/metadata.php
`use statement` has conflict between `BackBee\DependencyInjection\Container` and `BackBee\Renderer\Helper\container` so this PR aims to fix it.
Below the error I got:
``Cannot use BackBee\\DependencyInjection\\Container as Container because the name is already in use in __ROOT_DIR__/vendor/backbee/backbee/Renderer/Helper/metadata.php on line 26``
=> [Renderer] fixed metadata helper use statement conflict

Event/Dispatcher.php
There is a wrong behavior in `BackBee\Event\Dispatcher::triggerEvent()` which dispatch event of classcontent parents first and the specific one as last, which is the opposite expected behavior.
Admit that you have a content called `Autoblock` that extends `ContentSet`.
Wrong behavior on dispatch on `render` event:
1. `classcontent.render`
2. `contentset.render`
3. `autoblock.render`
Right and expected behavior:
1. `autoblock.render`
2. `contentset.render`
3. `classcontent.render`
So this PR aims to fix it.
=> [Event] fixed major behavior bug in Dispatcher::triggerEvent()

ClassContent/AbstractContent.php, ClassContent/ContentSet.php, Stream/ClassWrapper/Adapter/Yaml.php
* Introduce the exclusion of content type in accept arrays by prefixing classname with !
* Allow to define accept array in subcontent defintions, for example:
```
ColumnDivider:
properties:
name : Column divider
description: "Column divider"
category: [Block]
elements:
first_container:
type: BackBee\ClassContent\ContentSet
accept: [BackBee\ClassContent\Home\HomeArticleContainer]
maxentry: 1
```
=> [DROPZONE] #547 - enable user to drop blocks only in zones that can handle the right render mode

Rest/Controller/PageController.php
Changes for the following requests:
2. Pages that have subpages must be displayed before single pages
3. When creating a new page, display the page right after it parent . when reloading tree, page must go down after pages that have children
4. As soon as the toobar is loaded , load the tree in background task (for user to have it display quick when he'll click on it)(edited)
=> Tree adjustments refs:#5362

Config/Configurator.php, Config/Persistor.php, Config/Persistor/File.php, Config/Persistor/PersistorInterface.php, Config/Persistor/Registry.php, Config/Tests/ConfiguratorTest.php, Config/Tests/Persistor/FakePersistor.php
Introduce two optional configuration parameters to Config:config section:
* _persist_per_context_: persist overriding config taking account of the context (true by default)
* _persist_per_environment_: persist overriding config taking account of the environment (true by default)
=> [ENHANCEMENT] Allow to define the overriding configuration persist level

ClassContent/AbstractClassContent.php, ClassContent/AbstractContent.php
Currently when scalar is empty or string the json decode return null instead of return the current string.
I add test to check if the json_decode dont have error and if the json decode return null.
I propose to set null if json decode throw error cause if we keep the current value, serialize will be broken
Let me know @eric-chau @crouillon
=> Fix json encode on scalar element

Renderer/Helper/metadata.php
Currently, `Renderer/Helper/metadata::__invoke` throws warning when `$metadata` is `null`.
=> [Renderer] fixed metadata helper cause it throws warning on some use case

ClassContent/ContentSet.php
Options is used when value is not set on the YML.
=> Merge options with accept on contentset

ClassContent/AbstractClassContent.php, ClassContent/AbstractContent.php
Fixed `AbstractContent` has not main node attribute but `AbstractClassContent` does.
=> [ClassContent] fixed AbstractContent which has not main node attribute

ClassContent/ClassContentManager.php, ClassContent/Repository/ClassContentRepository.php, ClassContent/Tests/ClassContentPersistenceTest.php
Updated `ClassContentManager` and `ClassContentRepository::deleteContent()` to fix revision deletion on revert action. This PR aims to fix the issue [backbee/backbee-standard #594](https://github.com/backbee/backbee-standard/issues/594).
=> [ClassContent] fixed revision deletion on revert action

ClassContent/ContentSet.php
For accept parameters, we have two ways:
````
accept: ['MyContent', 'MyContent2']     =>   $options  
accept:      => $options['value']
type: ContentTypeSelector
value: ['MyContent', 'MyContent2']
````
=> Fix accept parameters creation for contentset

Config/services/security.yml
Removed duplicated `@security.voter.bb_role` in `security.access.decision_manager` service declaration.
=> [Security] updated its services to remove duplicated role voter

Controller/FrontController.php
For compatibility consideration, a WARNING level log is generated if a controller does not return an object Response and a new empty Response is created.
=> [BUGFIX] Ensure PostResponseEvent is triggered with a Response

Controller/FrontController.php
Currently, even if the dispatch of `kernel.request` event find a response, we don't take it in account and we keep running like it does not happen.
=> [Controller] updated FrontController to return response if exists after dispatch of  event

Bundle/BundleLoader.php
The first time a bundle is getting from the container, the method `::start()` is called. This is the expected behavior but we also have to invoke `::started()` method otherwise `::isStarted()` will always return `false`.
=> [Bundle] updated BundleLoader::buildBundleDefinition() to also call ::started()

Tests/Mock/MockBBApplication.php
Required for example to test bundles: the vendor dir is not in BackBee dir.
=> Allow to define a specific vendor directory in MockBBApplication

MetaData/MetaDataResolver.php
Hello,
I need the resolveConst() to be protected, to allow tht addition of other "constants" by a bundle override.
thx
=> MetaDataResolver : make resolveConst() method protected to allow proper overload by bundles

Console/Command/CleanOrphanContentCommand.php
Since short classnames are used for contents, the command `content:clean_orphan` must be updated to support them.
=> Fix CleanOrphan command to enable short classnames support

Rest/Controller/PageController.php
Related issue: https://github.com/backbee/backbee-standard/issues/707
Filters for page collection (created_before, created_before, modified_before and modified_after) were not working properly.
=> [LINK SELECTOR] search engine and page numbering are missing

Config/Configurator.php
The if condition in `Configurator::doBundleConfigExtend()` to determine if we should apply registry override or not is wrong. Currently even if `save_in_registry` is equal to `false` Configurator still run the override by registry process. This PR aims to fix it.
=> [Config] fixed Configurator::doBundleConfigExtend() to apply registry override only if save_in_registry exists and equals to true

Util/Doctrine/EntityManagerCreator.php
Updated the way `EntityManagerCreator` sets Doctrine metadata cache according to provided configuration. In some case the service identifier is replaced by the object on `Config` compilation. To prevent the fatal error due to it, I added additionnal checks to do the right thing on string and on object.
=> [Util] updated the way EntityManagerCreator sets Doctrine metadata cache

Installer/EntityFinder.php
Optimized `EntityFinder::getNamespace()` to reduce the string to tokenize by `token_get_all()`. In some cases the memory size limit is reached.
=> [Installer] optimized EntityFinder::getNamespace()

Installer/EntityFinder.php
Changed `EntityFinder::getNamespace()` to refer to the first occurence of `;` instead of `{` cause in some cases we broke comment block so `token_get_all()` generates PHP warnings.
=> [Installer] fixed EntityFinder::getNamespace() to refer to ';' instead of '{'

ClassContent/ClassContentManager.php, ClassContent/Repository/RevisionRepository.php, ClassContent/Revision.php, Config/route.yml, Rest/Controller/ClassContentController.php, Rest/Controller/RevisionController.php
Introduce three new REST services:
* `RevisionController::getAction()`: returns a specific revision by uid.
* `RevisionController::getCollectionByContentAction()`: Returns collection of revisions for a content.
* `ClassContentController::patchDraftAction()`: Reverts user's draft of a content to a specific revision number. Possible values for revision number are:
*  negative value: revert to current revision decrease from value.
*  empty value: revert to last committed revision.
*  positive value: revert to specific revision if exists.
=> Introduce Rest\RevisionController + Add ClassContentManager::revertToRevision() feature

ClassContent/Repository/ClassContentQueryBuilder.php
Updated `ClassContentQueryBuilder::addClassFilter` to ensure that requested classes are loaded cause sometimes we get error about classcontent that are not part of AbstractClassContent discriminators.
=> [ClassContent] updated ClassContentQueryBuilder::addClassFilter 

Config/Configurator.php
A project bundle configuration file (ie /repository/Config/bundle/.../config.yml) was overriding the initial config, requireing to repeat every unchanged initial values.
The fix allow to only store in the file the changed values
=> [Config] Fix bundle configuration extend by file

ClassContent/Traits/Element/FileJsonSerializeTrait.php
Added more checks to `FileJsonSerializeTrait::jsonSerialize()` to prevent error like this:
`PHP Warning: json_decode() expects parameter 1 to be string, array given in vendor/backbee/backbee/ClassContent/Traits/Element/FileJsonSerializeTrait.php on line 22`
=> [ClassContent] improved FileJsonSerializeTrait::jsonSerialize()

Rest/Controller/GroupController.php, Rest/Controller/MediaFolderController.php
As example, getting collections of BackBee\NestedNode\MediaFolder was never granted by ACL
=> [BugFix] Correction of some Rest\Security annotations

Console/Command/UpdateUsersRightsCommand.php
The correct field search is the name of the group.
Also take account of optional description
=> [BUGFIX] An existing group was looked for by its description

NestedNode/Repository/PageRepository.php
When a Section moves in tree (goes down in a parent and back to home), Pages levels was wrong.
This seams to fix the issue.
Test case
I have a Tree like this : 
- Category_1
- Article_1
- Category_2
- Article_2
- Category_3
- Article_3
I move Category_3 to Category_2 - OK
I move Category_3 to back to Home - FAIL (Category_3 is not visible on tree. Pages and sub-pages keeps old levels in database.)
Thanks a lot.
=> [Tree] fix pages levels for Section movements

Bundle/BundleLoader.php
Updated `BundleLoader::loadFullBundles()` to load every bundle's services first. Actually, we load every bundle completely one by one so `::loadRoutes()` is invoked too early. It means that only the first declared bundle can override `routing` service definition. Which is not what we want. This PR aims to fix it.
=> [Bundle] updated BundleLoader::loadFullBundles() to load every bundle services first

Bundle/Registry.php
before (with one index on here 2 column key and scope)
after (with one index for each of three column scope, key, type)
=> add unique index for each of three column instead one index for them

Bundle/BundleLoader.php
Today BundleLoader overrides:
- configuration of bundles threw folder `/reporository/bundle/<< bundleid >>/`
- services of bundles threw folder `/reporository/bundle/<< bundle basename >>/`
This PR aims to allow services overriding using bundleid but preserves the other one
=> Fix bundle overriding

CONTRIBUTING.md, README.md
Fix URLs on Readme and rename product to BackBee CMS
=> Rename BackBee into BackBee CMS

ClassContent/AbstractContent.php
This PR aims to avoid error like `PHP Fatal error:  Class name must be a valid object or a string in /vendor/backbee/backbee-php/ClassContent/AbstractContent.php on line 751` which occurs if classcontent that does not exist anymore still remain in your database and `bbapp.classcontent.exception_on_unknown_classname` parameter is setted to `false`.
=> updated AbstractContent::getData to ignore null type

Bundle/AbstractBundle.php, Bundle/Event/AbstractBundleEvent.php, Bundle/Event/BundleStartEvent.php, Bundle/Event/BundleStopEvent.php, Bundle/Listener/BundleListener.php
This PR introduces two new events:
* `bundle.<<bundle id>>.started` : dispatched after the bundle starts
* `bundle.<<bundle id>>.stopped` : dispatched after the bundle stops
=> Add new events dispatching

Routing/RouteCollection.php
This PR aims to improve `RouteCollection::getUriForSite` to preserve HTTP scheme if it is provided by Site's `server_name`.
=> [Routing] updated RouteCollection::getUriForSite to preserve scheme from Site if it exists

Rest/Controller/ResourceController.php
Uploading two images with the same original name in the same second generates one same filename.
So only one image is saved.
This patch replaces the descriminator time() by uniqid ('', true) to ensure the unicity of the filename.
=> [BUGFIX] Ensure unicity of a generated name for an uploaded file.

Rest/Controller/SecurityController.php
Currently, `SecurityController::authenticateAction` only encodes password with `md5`. This PR aims to change it by using the declared encoder for `BackBee\Security\User` in `security.yml`.
=> [Rest] updated SecurityController to encode password with declared encoder

Rest/Controller/Event/ValidateFileUploadEvent.php, Rest/Controller/ResourceController.php
This PR adds a new event: `ValidateFileUploadEvent`. This event is dispatched when a new base64 encoded file is uploaded. By default, BackBee accepts the upload of any files. In some cases, you may want to be able to restrict the upload of images only.
=> [Rest] updated ResourceController to dispatch ValidateFileUploadEvent

Event/Listener/PageListener.php
In some cases, `$notDeletedDescendants` is type of array so the method `::getItrator()` does not exist.
=> [Event] fixed PageListener to use count() instead of iterator->count()

Renderer/AbstractRenderer.php
While loading a bundle, the view directory of the bundle was included as first position, avoiding the overriding of its views.
Setting the default position to 1 ensures to keep the project veiw repository as the first one included while looking for templates.
=> [BUGFIX] Ensure the project view repository is always the first one included

Renderer/AbstractRenderer.php
While adding new layouts, helpers and scripts dir at default position 1, key mismatch and overriding occured
=> [BUGFIX] [Renderer] Fix insert new item in array at any position

Security/Authentication/AuthenticationManager.php
Because a SecurityException thrown by providers was not catch, the authentification process ended before the last authentication providers was called, disabling the possible providers defined after the core ones.
=> Catch SecurityException in AuthenticationManager

.travis.yml, composer.json
Resolved [#784](https://github.com/backbee/backbee-php/issues/784)
Due to an update of doctrine/common, php < 5.6 can no more be supported
=> [MISC] Remove support of PHP < 5.6
