- Logging/Logger.php
This step should not be done in Logger but in Appender\File cause logfile is only used in case that requested appender is Appender\File.
> [RFR] [Logging] #158 - removed validation logfile step from Logger

- Rest/EventListener/ExceptionListener.php
- Rest/Tests/EventListener/ExceptionListenerTest.php
Change the status code for an unknown user to 401 instead of 404
> #144 Change the status code for an unknown user to 401 instead of 404

- BBApplication.php
> [RFR] #168 + updated BBApplication::_initAnnotationReader to register a custom loader for backbee's annotations

- Rest/Controller/ClassContentController.php
> [Rest] #192 + fixed ClassContentController::getFormatParam

- Rest/Controller/ClassContentController.php
> [RFR] [Rest] #202 + updated ClassContentController::postAction

- ClassContent/AClassContent.php
- ClassContent/Tests/ClassContentTest.php
- ClassContent/Tests/Mock/MockContent.php
Added ``AClassContent::getDefaultImageName`` and associated tests. Updated ``AClassContent::jsonSerialize`` and added tests for ``AClassContent::jsonSerialize`` and ``AContent::jsonSerialize``.
> [RFR] [ClassContent] #213 updated ::jsonSerialize and added ::getDefaultImageName and associated tests

- Resources/js/bb5rteadapters/aloha.adapter.js
See #216.
The path is hardcoded and need to be updated too.
> Fixed aloha library path in adapter

- ClassContent/Repository/IndexationRepository.php
Before some tests, the probleme HHVM and php7 become from the method getParentContentUids in IndexationRepository.
> [ClassContent] fix IndexationRepository for HHVM and php7 #223

- Event/Event.php
- FrontController/Event/PostResponseEvent.php
- FrontController/Event/PreRequestEvent.php
- FrontController/FrontController.php
- Renderer/Event/RendererEvent.php
> [RFR] [FrontController] #221 application's dispatcher will dispatch event before and after request process

- ClassContent/AClassContent.php
> [RFR] [ClassContent] #231 updated AClassContent::jsonSerialize

- Bundle/BundleLoader.php
- Config/Configurator.php
- Config/Tests/ConfiguratorTest.php
- Config/Tests/PersistorTest.php
- Config/services/services.yml
> [RFR] [Config] #234 fixed Configurator to use bundle's right identifier

- Config/route.yml
- Rest/Controller/UserController.php
- Rest/Tests/Controller/LayoutControllerTest.php
- Rest/Tests/Controller/SecurityControllerTest.php
- Rest/Tests/Controller/UserControllerTest.php
- Security/Tests/Authorization/Voter/BBAclVoterTest.php
- Security/User.php
This not complete implementation of the issue #225 but is needed by backbee/BbCoreJs#17
> [rest] Complete rest user controller #225

- Config/services/serializer.yml
- FrontController/FrontController.php
- NestedNode/Listener/Serializer/PageListener.php
- Rest/Controller/ARestController.php
url entry is preserved, uri entry is added and contains the full qalifed URL for page
> [REST] PageController should return full qualified URL for pages

- Command/Tests/AclLoadCommandTest.php
- Config/route.yml
- Rest/Controller/GroupController.php
- Rest/Controller/SiteController.php
- Rest/Tests/Controller/AclControllerTest.php
- Rest/Tests/Controller/GroupControllerTest.php
- Rest/Tests/Controller/PageControllerTest.php
- Rest/Tests/Controller/SiteControllerTest.php
- Rest/Tests/Controller/UserControllerTest.php
- Security/Acl/Domain/SecurityIdentityRetrievalStrategy.php
- Security/Acl/Loader/YmlLoader.php
- Security/Group.php
- Security/Tests/Acl/Loader/YmlLoader.php
- Security/Tests/Authorization/Voter/BBAclVoterTest.php
- Tests/TestCase.php
This is a REST and Entity update of Group. The issue #227 still in working progress.
> [rest] Complete rest group controller #227

- Config/Configurator.php
- Config/Persistor/File.php
- Config/Persistor/Registry.php
> [RFR] [Config] #256 + updated the way keys are computed in File and Registry persistor

- CONTRIBUTING.md
Now, we can't push on master anymore.
All the team have to work on his own fork.
> Improved contributing: added Sync fork guide

- Security/User.php
Little update to transform json serialization from :
```json
"user": {
...
"_groups": []
...
}
```
to :
```json
"user": {
...
"groups": []
...
}
```
> [user] update serializer user definition

- Command/UpgradeToPageSectionCommand.php
Got strange error on ReflectionClass() with classname containing numbers.
This PR will have to be made on master also
> [Command] #267 - Rename command UpgradeFrom0_10To0_11Command.php to UpgradeToPageSectionCommand.php

- Config/events.yml
- Config/route.yml
- Event/Listener/RevisionListener.php
- Rest/Controller/ResourceController.php
- Add upload resource service (Move a file into a Tmp directory of BackBee)
- Add listener onFlush of a content revision (Move the file into a Media directory)
> [REST] add upload service

- Config/route.yml
- Rest/Controller/ARestController.php
- Rest/Controller/UserController.php
- Security/Group.php
- Security/User.php
> [wip] finalising and debuging rest user and group

- Config/route.yml
- Rest/Controller/UserController.php
- Rest/Tests/Controller/AclControllerTest.php
- Security/Repository/UserRepository.php
- Security/User.php
There is large cleaning in the routing (missing parameters principally)
Add 3 new methods in the user entity.
Add REST API key generation during the user creation.
> Add a public and private key generation and some routing fixes

- Rest/Controller/ResourceController.php
- Split main function
- Add upload from base64 src
> [REST] [Resource] + add upload from base64 src

- Config/route.yml
- NestedNode/Media.php
- NestedNode/Repository/MediaFolderRepository.php
- NestedNode/Repository/MediaRepository.php
- Rest/Controller/MediaController.php
- Rest/Controller/MediaFolderController.php
creating media and mediaFolder rest services
> 291 : creating media and mediaFolder services

- Renderer/Adapter/Twig.php
- Forget to replace an variable
> [Renderer] [Adapter] [Twig] + fix typo to replace  to cache_directory to cacheDirectory

- NestedNode/Builder/PageBuilder.php
Wrong change on setter function
> [NestedNode] + fix typo in PageBuilder

- Rest/Controller/MediaController.php
> [REST] [Media] + Change AclassContent to AbstractClassContent

- Config/events.yml
- Event/Listener/RevisionListener.php
Bad use of event cause of change the data into a flush event instead of a pre flush event.
> [Event] + change the event on flush to on pre flush for element file into RevisionListener

- ClassContent/ClassContentManager.php
- ClassContent/Repository/Element/FileRepository.php
- Event/Listener/RevisionListener.php
- Delete commitFile function into a commit function of ClassContentManager cause it used into RevisionListener
- Fix commitFile function from FileRepository
> [ClassContent] + Fix validation of file element

- ClassContent/ClassContentManager.php
- ClassContent/Revision.php
Conflict with draft on first commit
> [ClassContent] + fix commit of classcontent

- Renderer/Helper/isDebug.php
> creating isDebug helper

- ClassContent/ClassContentManager.php
Updated ``ClassContentManager::getThumbnailBaseFolderPath`` and ``ClassContentManager::updateClassContentImageUrl`` to looking for classcontent thumbnail in repository's resources folder and backbee's resources folder and not only in repository resources folder.
> [RFR] [ClassContent] updated the way ClassContentManager compute image url

- Rest/Controller/PageController.php
Currently redirect is always set as empty
> [Rest] Set null the redirect if empty on PageController

- Config/services/services.yml
- Resources/translations/messages.en.xlf
- Resources/translations/messages.fr.xlf
- Rest/Controller/LayoutController.php
> [WIP] - Translate layout status

- Rest/Controller/UserController.php
- Rest/EventListener/ValidationListener.php
- Rest/Tests/Controller/UserControllerTest.php
ping @ndufreche : as you said the problem was a missing validation rule on User creation.
I've added a limit of characters on User login and a test to check an exception is returned to BbCoreJs client.
Then, some code cleaning on UserControllerTest class.
> [RFR] Closes #129 - apply rules on user creation

- NestedNode/Builder/PageBuilder.php
- NestedNode/Page.php
- NestedNode/Tests/PageTest.php
- NestedNode/Tests/Repository/PageRepositoryTest.php
- Rest/Controller/PageController.php
- Rest/EventListener/ExceptionListener.php
- Rest/Tests/Controller/PageControllerTest.php
- Tests/TestCase.php
Now, when you try to archive or publish later a root page, an logical exception will be thrown by PHP Core.
Also, the state if a root page is no more updatable.
ping @ndufreche, is it enough from the "BbCoreJs" side ?
> Closes #132 - Root page should'nt be archivable, publishable or put offline

- NestedNode/Page.php
Added two methods ``Page::getCreatedTimestamp`` and ``Page::getModifiedTimestamp`` and annoted as JMS virtual property. It solves issue #228 by adding ``created`` and ``modified`` data to page rest api.
> [RFR] [NestedNode] added two methods to Page entity #228

- BBApplication.php
Cleaned up ``BackBee\BBApplication``:
- removed some unused attributes or methods
- updated methods and attributes names by removing ``_`` prefix
- respecting limit of 120 characters max by line
> updated BBApplication by removing some useless attributes and methods and updating coding style

- Rest/Controller/UserController.php
We need this specific event to not send email to each user creation ans send this email only if is created in Rest context.
> Dispatch rest.user.creation

- Rest/Controller/PageController.php
- Rest/Tests/Controller/PageControllerTest.php
- Rest/Tests/Controller/SiteControllerTest.php
- Rest/Tests/Controller/UserControllerTest.php
- Security/Authorization/Voter/BBAclVoter.php
- Security/Repository/UserRepository.php
- Security/Tests/Authorization/Voter/BBAclVoterTest.php
Fix some Acls issues and allow to apply rights on AbstractClassContent
> [ACL] #107 - Fix Acls voting

- Resources/scripts/Profiler/toolbar.html.twig
* Remove jQuery code, added native javascript.
* Fixed some styles and positionning
> Closes #134 - remove jQuery dependency from debug toolbar

- NestedNode/Repository/MediaRepository.php
Handling search by title and date in MediaRepository
> Handling search by title and date in MediaRepository

- Rest/Controller/GroupController.php
- Rest/Tests/Controller/AbstractRestControllerTest.php
- Rest/Tests/Controller/AclControllerTest.php
- Rest/Tests/Controller/ClassContentControllerTest.php
- Rest/Tests/Controller/GroupControllerTest.php
- Rest/Tests/Controller/LayoutControllerTest.php
- Rest/Tests/Controller/PageControllerTest.php
- Rest/Tests/Controller/SecurityControllerTest.php
- Rest/Tests/Controller/SiteControllerTest.php
- Rest/Tests/Controller/UserControllerTest.php
- Rest/Tests/Encoder/ContainerEncoderProviderTest.php
- Rest/Tests/EventListener/BodyListenerTest.php
- Rest/Tests/EventListener/ExceptionListenerTest.php
- Rest/Tests/EventListener/PaginationListenerTest.php
- Rest/Tests/EventListener/ValidationListenerTest.php
- Rest/Tests/Exception/ValidationExceptionTest.php
- Rest/Tests/Mapping/ActionMetadataTest.php
- Rest/Tests/Mapping/Driver/AnnotationDriverTest.php
- Tests/Config/security.yml
- Tests/TestCase.php
* Add security annotations on GroupController
* Rest tests are now executed as sudoer
* Rest tests can now be executed with this command ``phpunit --group=Rest``
> [RFR] - Added security rights on GroupController

- Rest/Controller/BundleController.php
- Rest/Tests/Controller/BundleControllerTest.php
- Rest/Tests/Controller/PageControllerTest.php
- Tests/Config/bundles.yml
- Tests/Config/config.yml
- Tests/Config/services.yml
- Tests/Mock/MockBBApplication.php
- Tests/Mock/MockConfigurator.php
- composer.json
This pull request solves #363.
* Add bundles to mock application
* Avoid configuration of bundles in mock application
* Tests
This pull request depends on https://github.com/backbee/BackBee/pull/366
> [RFR] - Bundle controller rights

- Rest/Controller/ClassContentController.php
* Add rights on Controller
* Checks tests
> [RFR] - Classcontent controller rights

- Config/route.yml
- Rest/Controller/LayoutController.php
- Rest/Tests/Controller/LayoutControllerTest.php
* remove some weirds controls on routes (is it part of spec ?)
* remove useless functions
* add tests for get|getWorkflowStates actions
> [RFR] - Added security and tests on Rest/LayoutController

- ClassContent/AbstractContent.php
- ClassContent/ClassContentManager.php
- ClassContent/Exception/InvalidContentTypeException.php
- Rest/Controller/ClassContentController.php
Updated ``BackBee\ClassContent\ClassContentManager::findOneByTypeAndUid`` to not trying to set draft if content is null.
Updated ``BackBee\Rest\Controller\ClassContentController::getAction`` to throw exception on not found content.
> [ClassContent] updated ClassContentManager::findOneByTypeAndUid and ClassContentController::getAction

- Rest/Tests/Controller/SecurityControllerTest.php
* Checked security (was OK)
* Checked and refactored a little bit tests
> Checked security and tests on Rest\SecurityController

- Rest/Controller/MediaFolderController.php
- Rest/Test/RestTestCase.php
- Rest/Tests/Controller/MediaFolderControllerTest.php
* Added security annotations
* Added tests
> [RFR] Mediafolder controller rights

- ClassContent/Repository/ClassContentRepository.php
- Rest/Controller/PageController.php
Currently ``ClassContent/Repository/ClassContentRepository::findPagesByContent`` does not return the expected result cause it relied on Doctrine lazy load which did not do the right result. So I resolved it by doing native SQL query.
> [ClassContent] fixed ClassContentRepository::findPagesByContent

- Rest/Controller/MediaFolderController.php
- Rest/Tests/Controller/MediaFolderControllerTest.php
ping @eric-chau missing test and (because of Murphy's law) related fix.
> Fixed Security annotation on postAction of MediaFolderController

- Rest/Controller/PageController.php
Updated ``PageController::patchAction`` to process ``is_hidden`` instead of ``is_visible`` for more coherence with PHP ``NestedNode\Page`` api. This PR is requested by @fkroockmann.
> [Rest] updated PageController::patchAction to process 'is_hidden' instead of 'is_visible'

- ClassContent/AbstractClassContent.php
- ClassContent/Listener/ClassContentListener.php
- ClassContent/Listener/RevisionListener.php
- ClassContent/Repository/ClassContentRepository.php
- Config/events.yml
- Rest/Controller/ClassContentController.php
- Rest/Controller/MediaController.php
This PR aims to fix every issues users met about ``ClassContent`` and ``Revision`` persistence and deletion.
> [ClassContent] fixed every processes about classcontent and its revision persistences

- NestedNode/Page.php
- NestedNode/Tests/PageTest.php
* Move validation to his own methods for publishing and archiving
* Apply some exceptions on business rules
* Added unit tests
> Refactor and improve archiving/publishing rules

- Rest/Controller/GroupController.php
- Rest/Tests/Controller/GroupControllerTest.php
An unification of the saving rules on group
see => backbee/BbCoreJs#694
> [REST] unify rules to save a group

- Rest/Controller/UserController.php
- Security/Group.php
- Security/User.php
> Upgrade group entity to add description

- NestedNode/Page.php
- NestedNode/Tests/PageTest.php
Currenlty, hasChildren don't count a deleted page.
> [NestedNode] + Fix hasChildren function into Page

- Util/ExtensionMimeTypeGuesser.php
> Added svg mime type guessing support

- Rest/Controller/UserController.php
- Rest/Tests/Controller/UserControllerTest.php
- Security/Tests/UserTest.php
- Security/User.php
- Tests/TestCase.php
- Generate API keys when need
- Add User() unit tests
> [User] #419 Generate API keys when API access is enabled

- Rest/Controller/PageController.php
* added authorisations of PATCH on archiving/publishing
REFS https://github.com/backbee/BbCoreJs/issues/746
> Added new authorisations on Page to entity patcher

- Rest/Controller/UserController.php
> set the raw password on user creation

- Rest/Controller/AbstractRestController.php
- Rest/Controller/ClassContentController.php
- Rest/Controller/PageController.php
- Rest/EventListener/ExceptionListener.php
Also send 403 status code on InsufficientAuthenticationException throwing
+ Fix user right on PageController
> Throw InsufficientAuthenticationException rather than AccessDeniedException on granted failed

- Rest/Controller/UserController.php
To avoid disconnection in toolbar bundle if you are not allowed to view a user
> Switch AccessDenied to InsufficientAuthentication in  user controler

- ApplicationInterface.php
- BBApplication.php
- Bundle/AbstractBundle.php
- Config/services/services.yml
- Controller/Event/PostResponseEvent.php
- Controller/Event/PreRequestEvent.php
- Controller/Exception/FrontControllerException.php
- Controller/FrontController.php
- Controller/MediaController.php
- Controller/ResourceController.php
- Renderer/Adapter/Twig.php
- Renderer/Adapter/phtml.php
- Rest/EventListener/ExceptionListener.php
- Rest/Tests/EventListener/BodyListenerTest.php
- Rest/Tests/EventListener/ExceptionListenerTest.php
- Rest/Tests/EventListener/PaginationListenerTest.php
- Rest/Tests/EventListener/ValidationListenerTest.php
- Tests/Mock/ManualBBApplication.php
- Tests/Mock/MockController.php
Merged ``Controller`` and ``FrontController`` components. More details in #388.
> [FrontController] merged Controller and FrontController components #388

- BBApplication.php
- composer.json
- Updated version from ``1.0.0-DEV`` to ``1.1.0-DEV``
- added authors to ``composer.json``
> updated project version to 1.1.0-DEV and added authors to composer.json

- ClassContent/AbstractClassContent.php
Currenlty, this function use a old mangement of parameters
> Fix getMode function in AbstractClassContent

- ClassContent/Listener/ClassContentListener.php
- ClassContent/Tests/Listener/ClassContentListenerTest.php
- Config/events.yml
Subscribing to 'rest.controller.classcontentcontroller.getAction.postcall' event
and add the available rendermode if the contant have a rendermode param
> Add automatically list of rendermode if the content has rendermode param

- backbee
ping @eric-chau => refs https://github.com/backbee/backbee-standard/pull/200
I may need this to complete my pull request on backbee standard.
> Added Context optional parameter

- Rest/Controller/ClassContentController.php
Solve backbee/backbee-standard#276
> [REST] Fix ClassContentController::postAction() ACL control always fail

- Config/Config.php
- Config/Persistor/File.php
- Config/Persistor/PersistorInterface.php
- Config/Persistor/Registry.php
- Config/Tests/ConfigTest.php
Some refactorings since I have read this component to write docs
> Config component review

- BBApplication.php
Fix annotation autoloading brokes by Symfony 2.7
> Fix annotation autoloading which is broken by Symfony 2.7

- Bundle/Registry/Repository.php
Little correction on a old copy past fail.
> registry repository count function bug fix

- Config/events.yml
- Rest/Tests/Controller/LayoutControllerTest.php
- Workflow/Listener/PageListener.php
- Workflow/ListenerInterface.php
- Workflow/State.php
- Workflow/Tests/Mock/CallableListener.php
- Workflow/Tests/Mock/StateListener.php
- Workflow/Tests/PageListenerTest.php
- Workflow/Tests/StateTest.php
This PR aims to resolve https://github.com/backbee/backbee-standard/issues/295 to resolve and improves ``BackBee\Workflow\State`` and ``BackBee\Workflow\Listener\PageListener`` by adding tests; it also fix the way we handle state's listener.
> [RFR] [Workflow] updated PageListener and state ListenerInterface

- .travis.yml
- Controller/FrontController.php
- Util/Ftp.php
This is a "technical debt" pull request.
I don't know how to test to be sure this update wont break anything /c @crouillon 
Also, I have updated travis configuration to test PHP 7.0 and remove hhvm-nightly /c @eric-chau
> Fixed majors issues

- .scrutinizer.yml
Added all ``Tests`` folders to excluded paths
> Improve scrutinizer configuration

- BBApplication.php
Changing bad content on getLogging function
> Correcting bad documentation

- Translation/Translator.php
> Typo correction into commentaries

- composer.json
ping @eric-chau, sorry about that, now fixed.
(I will also cherry-pick this one into 1.0.x branch)
> Fixed testing dependencies

- BBApplication.php
type of correction
- Add backslash on complete namespace
- Add comments on uncommented methods
- Return the Interfaces instead of the object him self or the abstract
> [comment] update BBAplication php doc

- Rewriting/UrlGenerator.php
Don't take account of deleted pages while checking the uniqueness of an URL to avoid a possible NonUniqueResultException throwed by Doctrine
> [UrlGenerator] Fix URL generator

- Cache/File/Cache.php
- Renderer/AbstractRenderer.php
- Renderer/Renderer.php
- Rest/Controller/AclController.php
- Rest/Controller/MediaFolderController.php
- Rewriting/UrlGenerator.php
- composer.json
Bumped utils 2.0 which is compatible with php7 and introduce ``StringUtils`` instead of ``String``.
> Removed deprecated class String uses from BackBee core

- BBApplication.php
- Cache/AbstractCache.php
- Cache/AbstractExtendedCache.php
- Cache/CacheExtendedInterface.php
- Cache/CacheInterface.php
- Cache/DAO/Cache.php
- Config/Config.php
- Event/Listener/CacheListener.php
Added an interface instead of use `AbstractCache` as the contract for each Cache adapter.
> [Cache] Introduce a new CacheInterface

- Event/Listener/CacheListener.php
Cleaned CacheListener according to sensiolabs Insight
> Removed unused statment on CacheListener

- Annotations/ChainAnnotationReader.php
- Bundle/AbstractBundleController.php
- ClassContent/CategoryManager.php
- ClassContent/ClassContentManager.php
- ClassContent/Listener/ClassContentListener.php
- ClassContent/Listener/IndexationListener.php
- ClassContent/Repository/ClassContentRepository.php
- Event/Listener/LayoutListener.php
- Installer/Database.php
- Installer/Fixture.php
- Logging/Appender/Output.php
- Logging/Logger.php
- NestedNode/MediaFolder.php
- NestedNode/Repository/NestedNodeRepository.php
- Util/Transport/SFTP.php
Some cleaning in order to reduce bug risks (unused variables/functions)
> Remove unused

- BBApplication.php
- Bundle/AbstractBundleController.php
- Cache/CacheExtendedInterface.php
- Cache/CacheInterface.php
- ClassContent/AbstractClassContent.php
- ClassContent/AbstractContent.php
- ClassContent/ClassContentManager.php
- ClassContent/Repository/ClassContentRepository.php
- Console/Command/ApplicationUpdateCommand.php
- Event/Listener/CacheListener.php
- NestedNode/AbstractNestedNode.php
- Renderer/Helper/bundleAdminForm.php
- Renderer/Helper/bundleAdminLink.php
- Renderer/Helper/dateHelper.php
- Rest/Controller/LayoutController.php
- Rest/Controller/PageController.php
- Rest/Controller/SecurityController.php
- Workflow/State.php
* removed unused use statments
* refactored ``CacheListener`` to check instance only on ``CacheExtendedInterface``
> Remove unused use statments

- Profiler/DataCollector/ConfigDataCollector.php
- Resources/scripts/Collector/config.html.twig
- Resources/scripts/Profiler/layout.html.twig
Fixed the informations:
* removed useless phpinfo option (not work as expected, will be re-introduced as a new feature later)
* added environment information
* added context application information
* fixed BackBee version display in panel
> Improved configuration panel

- Logging/Logger.php
- NestedNode/Repository/MediaFolderRepository.php
- NestedNode/Repository/MediaRepository.php
- NestedNode/Repository/PageRepository.php
- NestedNode/Repository/SectionRepository.php
- Renderer/Renderer.php
- Rest/Controller/ClassContentController.php
- Rest/Controller/MediaFolderController.php
- Rest/Controller/PageController.php
- Rest/Controller/TestController.php
- Routing/RouteCollection.php
- Security/Acl/AclManager.php
* removed unused variables
* removed unused functions
> [Locked] reduced technical debt

- Bundle/AbstractBundleController.php
> fixed issue 509: added getBundle() to AbstractBundleController

- Rest/Controller/PageController.php
- Rest/Tests/Controller/PageControllerTest.php
This PR is Work In Progress and depend of other updates, in particular in backbee/BbCoreJs.
Add new query param "root" and add the possibility ti use getCollectionAction as a real getCollection.
> [RFR] Create a REST v2 for getCollectionAction from PageController

- Event/Listener/ExceptionListener.php
See => https://insight.sensiolabs.com/projects/8e55fbb8-0902-4666-8459-ed5662e220c3/analyses/122
I have introduced a major issue, this pull request aims to fix it.
> fixed missing use statment

- Event/Listener/ExceptionListener.php
in ExceptionListener.
ping @eric-chau
> get the request from application

- ClassContent/AbstractClassContent.php
- ClassContent/AbstractContent.php
- ClassContent/ClassContentManager.php
- ClassContent/ContentSet.php
- ClassContent/Listener/ClassContentListener.php
- ClassContent/Listener/RevisionListener.php
- ClassContent/Repository/ClassContentQueryBuilder.php
- ClassContent/Repository/ClassContentRepository.php
- ClassContent/Repository/IndexationRepository.php
- ClassContent/Repository/RevisionRepository.php
- ClassContent/Revision.php
- ClassContent/Tests/ClassContentTest.php
- Console/Command/UpgradeToPageSectionCommand.php
- Console/Command/UpgradeToShortClassnameCommand.php
- Console/Finder/CommandFinder.php
> [ClassContent] Store short content classnames in Db

- Config/route.yml
- NestedNode/KeyWord.php
- NestedNode/Repository/KeyWordRepository.php
- Rest/Controller/KeywordController.php
- Rest/Tests/Controller/KeywordControllerTest.php
> keyword rest service

- Config/events.yml
- Config/route.yml
- Console/Command/UpgradeToSectionHasChildrenCommand.php
- Event/Listener/PageListener.php
- NestedNode/Page.php
- NestedNode/Repository/PageRepository.php
- NestedNode/Repository/SectionRepository.php
- NestedNode/Section.php
- NestedNode/Tests/Repository/PageRepositoryTest.php
- Rest/Controller/PageController.php
- Rest/Exception/NotModifiedException.php
- Rest/Tests/Controller/PageControllerTest.php
Add the possibility to modify a page collection :
- state to online
- state to offline
- state to delete
- parent node
This Action is based on the current `ClassContent::putCollectionAction` implementation.
> [RFR][REST][PAGE] creating putCollectionAction

- Rest/Controller/GroupController.php
- Rest/Tests/Controller/GroupControllerTest.php
GroupController::getCollectionAction() must return groups of the current site AND common groups (ie with $_site null)
> [Rest] Update GroupController::getCollectionAction()

- ClassContent/Listener/ClassContentListener.php
> [ClassContent] Fix parameter name in ClassContentListener::onApplicationInit()

- ApplicationInterface.php
- Config/services/routing.yml
- Routing/RouteCollection.php
- Routing/Tests/RouteCollectionTest.php
- Tests/Mock/ManualBBApplication.php
- use the request values if available
- introduce bbapp.routing.default_protocol in container parameters
- add ApplicationInterface::isClientSAPI() (CR?)
> [Routing] Change RouteCollection:getUri()

- NestedNode/Repository/PageQueryBuilder.php
- Rest/Controller/UserController.php
- Rest/Test/RestTestCase.php
- Security/Authentication/Provider/UserAuthenticationProvider.php
- Security/Token/PublicKeyToken.php
- Security/Token/UsernamePasswordToken.php
all issues have been created on backbee standard repository
> remove all @todo

- ClassContent/Repository/ClassContentRepository.php
- Event/Listener/RewritingListener.php
No content were found by this method because of unknown classname
> [ClassContent] Fix ClassContentRepository::getLastByMainnode()

- ApplicationInterface.php
- ClassContent/AbstractClassContent.php
- ClassContent/AbstractContent.php
- ClassContent/CategoryManager.php
- ClassContent/ClassContentManager.php
- ClassContent/Element/Image.yml
- ClassContent/Iconizer/ChainIconizer.php
- ClassContent/Iconizer/IconizerInterface.php
- ClassContent/Iconizer/PropertyIconizer.php
- ClassContent/Iconizer/ThumbnailIconizer.php
- Config/services/services.yml
- Tests/Mock/ManualBBApplication.php
See issue: https://github.com/backbee/backbee-standard/issues/327
> [ClassContent] Add content property iconized-by

- Rest/Controller/PageController.php
Fix some typos and use order by in each case.
> [REST] Fix some typos in getCollection of page

- NestedNode/Repository/PageRepository.php
- NestedNode/Repository/SectionRepository.php
- NestedNode/Tests/Repository/PageRepositoryTest.php
- Rest/Controller/PageController.php
- Rest/Tests/Controller/PageControllerTest.php
Resolves : 
- https://github.com/backbee/backbee-standard/issues/399
> [TREE] Fix moving page in a non-section page

- ClassContent/AbstractContent.php
Updated ``AbstractContent::computeElementsToJson()`` to always return elements key whatever its values.
ping @crouillon, @fkroockmann.
> [ClassContent] updated AbstractContent::computeElementsToJson() 

- Config/route.yml
- Rest/Controller/KeywordController.php
> [REST] Add get action for keyword

- Config/route.yml
- Rest/Controller/KeywordController.php
- Rest/Tests/Controller/KeywordControllerTest.php
> New keyword services

- ClassContent/ClassContentManager.php
This PR will fix https://github.com/backbee/backbee-standard/issues/440.
To be concise, in some cases Doctrine doesn't know every classcontent classnames while they are used as factors in request to database. So we force the autoloading of it to avoid this issue.
> [ClassContent] on content commit we force autoload of classcontent classes

- Rest/Tests/Controller/SiteControllerTest.php
- Site/Site.php
I add missing annotation and remove excess annotation
> [Site] add missing annotation and remove excess annotation

- ClassContent/ClassContentManager.php
- Rest/Controller/ClassContentController.php
Updated ``BackBee\Rest\Controller\ClassContentController::postAction`` to also handle elements and parameters data if it is also passed as request parameters.
Ping @crouillon, @fkroockmann.
> updated creation of classcontent to handle elements and parameters data

- NestedNode/Page.php
- Rest/Controller/PageController.php
- Rest/EventListener/ExceptionListener.php
- Rest/Tests/Controller/PageControllerTest.php
- Site/Layout.php
https://github.com/backbee/backbee-standard/issues/457
> Add final layout management

- Config/route.yml
I add authorisation for capital letter in routes
> [Routing] add capitalized car to routes

- Rest/Controller/PageController.php
> fixing pageController

- Bundle/BundleControllerResolver.php
I've fixed bad english, and used sprintf.
> Fixed typo in BundleControllerResolver exception label

- ClassContent/AbstractClassContent.php
- ClassContent/AbstractContent.php
- ClassContent/ClassContentManager.php
- ClassContent/Repository/RevisionRepository.php
- ClassContent/Revision.php
Commit and revert of content's draft does not work fine sometimes. This PR aims to fix it.
> [ClassContent] updated and fixed revert and commit of contents drafts

- ClassContent/Listener/RevisionListener.php
If the file are upload on remote server, the stat function can not be used.
> Fix stat for image upload

- ClassContent/Repository/ClassContentQueryBuilder.php
- Rest/Controller/ClassContentController.php
Now we can :
/res/1/classcontent?uids=foo,bar
> Allow to add multiple uid as criteria for classcontent::getCollection

- Rest/Controller/ClassContentController.php
Explode return an non empty array, add array_filter for remove this case
> Fix classcontent getcollection call

- Rest/Controller/KeywordController.php
adding exception to KeywordController
> adding exception to KeywordController

- Rest/EventListener/ExceptionListener.php
https://github.com/backbee/backbee-standard/issues/492
> Catch RuntimeExcepion for mailer not available

- Stream/ClassWrapper/Adapter/Yaml.php
For example we can set the accept of upload for file like:
```
elements:
file:
type: BackBee\ClassContent\Element\File
label: fichier
extra:
dropzone:
acceptedFiles: '.pdf'
```
> Add extra for add special config in elements part of yml

- Rest/Controller/KeywordController.php
> removing ACL for KwController

- NestedNode/Repository/KeyWordRepository.php
- Rest/Controller/KeywordController.php
enable pagination to kw rest api
> enable pagination to kw rest api

- Rest/Controller/ClassContentController.php
Fix if draft dont have content
> Fix if draft dont have content

- Rest/EventListener/PaginationListener.php
> fixing pagination listener

- Rest/EventListener/PaginationListener.php
fixing pagination eventListener
> fixing pagination eventListener

- Bundle/BundleLoader.php
- Config/services/services.yml
Allow to dump then restore the bundleInfos array allowing to find bundle Id from its path
> [Bundle] Define BundleLoader as dumpable service

- ClassContent/Repository/IndexationRepository.php
For element contents no parent uids were returned
> [ClassContent] Fix IndexationRepository::getParentContentUids()

- ClassContent/ClassContentManager.php
- ClassContent/Repository/Element/KeywordRepository.php
> [Keyword] Update Keyword to Content joins

- ClassContent/AbstractClassContent.php
This PR aims to allow subclass to override parent class parameters.
> [ClassContent] updated AbstractClassContent::defineParam()

- Rest/Controller/PageController.php
Currently the deletion of page don't have rights
> Add right for page deletion

- ClassContent/Repository/Element/KeywordRepository.php
updated ``BackBee\ClassContent\Repository\Element\KeywordRepository::updateKeywordLinks()`` to put third argument as optional.
> [ClassContent] updated Element\KeywordRepository::updateKeywordLinks()

- Rest/Tests/Controller/KeywordControllerTest.php
Added tests for KeywordController, sorry for bad remote
> Added tests

- Util/Buffer.php
Print is display only on debug mode
> Add debug in Buffer

- Config/services/services.yml
We need theses services to be available as we may override them.
> remove hidden services

- ClassContent/AbstractClassContent.php
- ClassContent/AbstractContent.php
If an element is null, we need to retrieve a fake element
> Fix retrieve of data when an element is null

- ClassContent/Repository/ClassContentRepository.php
enabling search by uid in contentSelector
> enabling search by uid in contentSelector

- Config/Config.php
Currently several same config is not merged.
Wait merge of https://github.com/backbee/utils/pull/5
> Fix override of config to merge several config instead of replace

- Config/events.yml
- Config/services/services.yml
- MetaData/Listener/MetaDataListener.php
- MetaData/MetaData.php
- MetaData/MetaDataBag.php
- MetaData/MetaDataResolver.php
- MetaData/MetaDataResolverInterface.php
- MetaData/Tests/MetaDataBagTest.php
- MetaData/Tests/MetaDataResolverTest.php
- MetaData/Tests/MetaDataTest.php
- Renderer/Helper/metadata.php
- Rest/Controller/PageController.php
- Introduce MetaDataResolver as service
- Move MetaDataListener in package
> Refactoring metadata computing

- BBApplication.php
- ClassContent/Listener/ClassContentListener.php
- Util/Doctrine/EntityManagerCreator.php
Allow BackBee to start without doctrine.yml
> Add tests on entityManager validity

- Security/Listeners/UsernamePasswordAuthenticationListener.php
Dispatch ```security.interactive_login`` event when an user is authentified.
> Added security.interactive_login event

- ClassContent/Repository/ClassContentQueryBuilder.php
- ClassContent/Repository/ClassContentRepository.php
- NestedNode/Repository/MediaRepository.php
- Rest/Controller/ClassContentController.php
- Rest/Controller/MediaController.php
fixing pagination for medialibrary
> fixing pagination for medialibrary

- ClassContent/AbstractClassContent.php
- ClassContent/Indexes/OptContentByModified.php
- ClassContent/Repository/ClassContentRepository.php
Added indexes for:
- ClassContent's label
- OptContentByModified's created field
Improved ClassContentRepository to not use Paginator for better performance.
> [ClassContent] added MySQL index for OptContentByModified and improved ClassContentRepository pagination

- Rest/Controller/ClassContentController.php
> Optimize definitions call

- NestedNode/Repository/PageRepository.php
- NestedNode/Tests/Repository/PageRepositoryTest.php
- Rest/Controller/PageController.php
Fix toTrash() method.Avoid EntityManager to flush on repository.
Move flush to Controller.
Update unit tests.
> Page Repository : fix toTrash action

- Rest/Controller/ClassContentController.php
Optimizing 350ms
500 -> 150 ms
> [Rest] Add classcontent categories to cache

- ClassContent/Repository/ClassContentRepository.php
- Config/route.yml
- NestedNode/Repository/PageRepository.php
- NestedNode/Repository/SectionRepository.php
- Rest/Controller/PageController.php
* Introduce new REST action in PageController: deleteCollectionAction() to handle multi-delete request
* Refactoring of softDelete (ie only state change to trash)
* Fix hardDelete (ie removing from the db)
> [PAGE MANAGEMENT] refs:520 delete page and delete trash is KO

- Rest/Controller/BundleController.php
Related issue: https://github.com/backbee/backbee-standard/issues/576
Cache optimisation on my machine: ~450 ms down to ~215 ms
> [PLUGINS] set cache on bundle list

- ClassContent/ContentSet.php
Now we can change directly the accept in parameter of content.
When a param "accept" is saved the accept of content is synchronized with the param
> Synchronize accept param with accept of content

- NestedNode/Repository/MediaRepository.php
- Rest/Controller/MediaController.php
Enabling to find if a media is linked to a content
> Enabling to find if a media is linked to a content

- ClassContent/AbstractContent.php
Add main node state to know if the content have them page online or not
> Add main node state for content

- ClassContent/ContentSet.php
The function chain is currently not available on Contenset
> Add return this on ContentSet::setParam function

- Console/Command/ApplicationUpdateCommand.php
- Console/Command/CreateSudoerCommand.php
- Console/Command/CreateWebsiteCommand.php
- Console/Command/UpdateUsersRightsCommand.php
- bbapp:update 
- adjusted to accept host/port/user/password as options
- drop all tables
- bbapp:create_site
- create a new website entry in site table
- creates the layouts and the root page
- bbapp:create_sudoer
- creates a new sudoer
- users:update_rights
- updates the user group rights
- posibility to create a new user and assign a usergroup
> Reset commands

- Console/Command/CreateWebsiteCommand.php
- "array_column" is suported only by PHP 5 >= 5.5.0
- made both options mandatory "site_label" & "site_domain"
> Removed array_columun function - not suported by PHP 5.4

- Rest/Controller/PageController.php
Fix for: https://github.com/backbee/backbee-standard/issues/658
Added restore option.
> Restoring trash page #658

- Resources/scripts/ContentSet.phtml
- Resources/scripts/Element/attachement.phtml
- Resources/scripts/Element/file.phtml
- Resources/scripts/Element/image.phtml
- Resources/scripts/Element/link.phtml
- Resources/scripts/Element/select.phtml
- Resources/scripts/Element/text.b.phtml
- Resources/scripts/Element/text.div.phtml
- Resources/scripts/Element/text.footer.phtml
- Resources/scripts/Element/text.h1.phtml
- Resources/scripts/Element/text.h2.phtml
- Resources/scripts/Element/text.h3.phtml
- Resources/scripts/Element/text.label.phtml
- Resources/scripts/Element/text.p.phtml
- Resources/scripts/Element/text.phtml
- Resources/scripts/Element/text.span.phtml
Still have some phtml views that have reference to datacontent helper but it does not exist anymore. So this PR aims to fix it.
> removed use of datacontent helper which does not exist anymore

- Console/Command/CreateWebsiteCommand.php
Hello, I improved some "exit codes" and "console exceptions" in order to make the command compatible with calls from another console commands or from a web controller.
> Console command (bbapp:create_site) compatibility improvements

- BBApplication.php
- CHANGELOG-1.1.md
- Rest/Tests/Controller/BundleControllerTest.php
- composer.json
> Release v1.1.0

- Rest/Controller/ResourceController.php
- Rest/Tests/Controller/ResourceControllerTest.php
https://github.com/backbee/backbee-standard/issues/636
> 636 - add width and hight to the media infos

- ClassContent/Repository/RevisionRepository.php
Surrounded `RevisionRepository::getAllDrafts` with `try-catch` to handle corrupted drafts.
> [ClassContent] updated RevisionRepository to handle corrupted drafts

- ClassContent/ClassContentManager.php
https://github.com/backbee/backbee-standard/issues/689
Set the main node property to content drag & dropped in a main column of a page.
> 689 - Check if link is created between page and content

- Rest/Controller/MediaController.php
Updated `MediaController::getCollection` to allow search media by content uid.
> [Rest] updated MediaController::getCollection to allow find by content uid

- NestedNode/Repository/MediaRepository.php
- Rest/Controller/MediaController.php
Refactored `MediaRepository` and `Rest\Controller\MediaController` according to @mickaelandrieu comments. Thank you @mickaelandrieu.
> [Media] refactored MediaRepository and Rest/Controller/MediaController

- BBApplication.php
- Util/Doctrine/EntityManagerCreator.php
Allow to write in log file the last fatal error catched, especially database connection errors.
> Add registered method to handle fatal errors

- ClassContent/Repository/IndexationRepository.php
Avoid a 'Array to string conversion' notice while invoking the method.
> [BugFix] Fix IndexationRepository::getNodeUids()

- ClassContent/ClassContentManager.php
Updated `::commit()` and `::revert()` so the second argument is optional. if it is not provided, the content is fully commited of reverted.
> updated ::commit() and ::revert() of ClassContentManager

- Rest/Controller/KeywordController.php
- Rest/Tests/Controller/KeywordControllerTest.php
/rest/2:/keyword?uids=uid1,uid2,.. is now accepted by the service
> [REST] KeywordController::getCollectionAction() accepts now uids parameter

- ClassContent/Repository/RevisionRepository.php
This issue may appear if you upgrade BackBee's version and especially when you didn't import every classcontent type. This PR aims to avoid runtime exception by deleting these revisions that belong to old content.
> [ClassContent] updated RevisionRepository::getAllDrafts to delete revision of unknown content

- Event/Listener/PageListener.php
https://github.com/backbee/backbee-standard/issues/730
> 730 - tree is empty after deleting a page with sub-pages

- NestedNode/Repository/SectionRepository.php
Fix recursive delete for a page with sub-sections
Thanks @crouillon for your help.
> fix delete page with section

- ClassContent/Repository/ClassContentRepository.php
Related issue: https://github.com/backbee/backbee-standard/issues/742
> [CONTENT SELECTOR] hide content that not are not linked to pages

- DependencyInjection/ContainerBuilder.php
This PR adds the parameter `bbapp.root.dir` into container.
> [DependencyInjection] added project root directory into container's parameters

- Config/route.yml
- Rest/Controller/MediaFolderController.php
Find ancestors for media folder
Issue: https://github.com/backbee/backbee-standard/issues/741
> remember media tree opening after refresh #741

- Security/Authentication/Provider/UserAuthenticationProvider.php
Fix this error : no authenticationprovider found for token of class usernamepasswordtoken
> fix authentication method to return a boolean.

- Rest/Controller/AbstractRestController.php
- Rest/Controller/ClassContentController.php
- Rest/Controller/KeywordController.php
Preserve the order of the elements
> Sort elements by uids preserve order

- Resources/scripts/Collector/routing.html.twig
On some OS the routes array is not indexed by number
> Fix loop on profiler templates

- Console/Command/UpdateUsersRightsCommand.php
- Security/Group.php
- Security/Tests/Authorization/Voter/BBAclVoterTest.php
- Security/User.php
see https://github.com/backbee/backbee-php/issues/364
> [#364] ACL on groups: Group needs to implements ObjectIdentifiableInterface

- Rest/Controller/MediaController.php
Modifications made in  the postAction method.
> Enabling us to change the mediafolder of a media

- NestedNode/Page.php
Resolve the issue in reference
> [#786] Page publication date

- Console/Command/UpdateUsersRightsCommand.php
Refactor command code and add some help info.
Also remove the possibility to create a new user with this command
> Refactor command UpdateUsersRightsCommand

- Security/Authentication/AuthenticationManager.php
This PR aims to fix issue #792.
> [Security] fixed error 500 which is raised on wrong password #792

- Stream/ClassWrapper/Adapter/Yaml.php
This new event is triggered just after the YAML file parsing and just before the PHP class build.
It gets a read/write `data` argument containing the array representation of the parsed yaml.
> Add classcontent.streamparsing event dispatching

- Rest/Controller/SecurityController.php
Reverts backbee/backbee-php#796
> Revert "[#795] - [Authenticate] - Fix headers for Chrome 60"
